### ISSUE TITLE
Resource import order to overwrite partial data

### ISSUE THREAD

**Issue by vimishor** [kherge-abandoned/php-wise#13]
If I want to overwrite partial data from an imported resource, I need to list that file first, which is confusing.

For example, if I want to overwrite "parameters.yml::key2" from file "parameters_dev.yml", at this point in time I should do it like this:

``` yaml
# file: parameters.yml
key1: value1
key2: value2
key3: value3

# file parameters_dev.yml
key2: value20

# config.yml
imports:
  - { resource: parameters_dev.yml }
  - { resource: parameters.yml }
```

I would expect that `parameters_dev.yml` to be listed in config.yml after `parameters.yml`:

``` yaml
# config.yml
imports:
  - { resource: parameters.yml }
  - { resource: parameters_dev.yml }
```
