### ISSUE TITLE
Support non-scalar references

### ISSUE THREAD

**Issue by ghost** [kherge-abandoned/php-wise#3]
At the moment only scalar references are supported,

``` yaml
my_config:
    scalar_value: "the value: %my_config.value%" # this works
    value: 123
```

but non-scalar values used in any context will generate an exception.

``` yaml
my_config
    non_scalar_value: %my_config.value% #generates an exception
    value:
        integer: 123
```

The latter example should be supported, but not when used inline with another configuration parameter value (the first example).
